### ISSUE TITLE
Initial message tests

### ISSUE THREAD

**Issue by lukeswitz** [Root-Down-Digital/DragonSync-iOS#1]
## Tasks:

- [x] Verify reception of messages sent over multicast using hardcoded addressing.

- [x] Receive both esp32 and standard CoT messages as transmitted by the official [dragonsync](https://github.com/alphafox02/DragonSync) tooling methodology. 

- [ ] Verify all parsed logic from these messages is accurate

**Comment by lukeswitz** [comment]
done and done, true wardragon needed to verify

**Comment by lukeswitz** [comment]
need to parse the system info better

**Comment by lukeswitz** [comment]
Working. Updated UI for status
